services:
  marketplace-feed-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    env_file:
      - ./dev.env
    container_name: marketplace-feed-api
    volumes:
#      - /home/kinoko/logs/marketplace-feed-api:/logs
      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33303:33303"
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:18.0-alpine
    restart: always
    env_file:
      - dev.env
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:

volumes:
  pg_db: