services:
  marketplace-feed-api:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    env_file:
      - ".env"
    image: marketplace-feed-api
    container_name: marketplace-feed-api
    volumes:
      - /home/kinoko/logs/marketplace-feed-api:/logs
    #      - ./logs:/logs                             # Для отладки на windows машине
    networks:
      - backend
    ports:
      - "33303:33303"

networks:
  backend:
    external: true
