logging:
  config: 'classpath:log4j2.yml'
  level:
    com.netflix.discovery.shared: error
    com.vpr42.marketplacefeedapi.config.authorization: error

spring:
  servlet:
    multipart:
      max-file-size: 5MB
  application:
    name: marketplace-feed-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://kinoko.su:5432/mp_db_dev
    username: mp_dev_user
    password: mp_dev_passwd
    driver-class-name: org.postgresql.Driver

app:
  minio:
    login: kinadmin
    password: Kinok0Jap17096065
    bucket: mp-avatars
    urls:
      api: http://minio:9000
      public: https://bobr.kinoko.su/api/v1/buckets/mp-avatars/objects/download?prefix=
  cover:
    allowedExtensions: .jpg, .jpeg, .png, .bmp, .webp

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://marketplace-eureka:33307/eureka

springdoc:
  api-docs:
    enabled: true
    path: /api/feed/docs
  swagger-ui:
    csrf:
      enabled: true
    path: /api/feed/swagger

server:
  port: 33303
